### ISSUE TITLE
Usage on Non-SPA sites

### ISSUE THREAD

**Issue by brainyl** [vuejs-templates/webpack-simple-2.0#3]
I am currently having issues using this template to spice up my non-spa application. I get "Failed to mount component: template or render function not defined. (found in root instance)" whenever i try to run the application on the browser.

Previously, I was able to use the body as the el and quickly have my website using Vue and Webpack. Is there something I am not doing right or must I building a SPA application to use Vue-loader?

**Comment by mzgajner** [comment]
To start, this is probably a bad place to post issues. If you have problems with vue-cli, use the [main repo](https://github.com/vuejs/vue-cli), this is just a repository of a particular template.

Anyway, you'll have to provide more information, but generally you shouldn't have issues. If you bootstrap an app from this template (webpack-simple-2.0), you get an index.html file that includes the following element: `<div id="app"></div>`. This is where Vue hooks up (see main.js where it's instantiated). All the JavaScript is also included in that same index file with `<script src="dist/build.js"></script>`.

So all you need to do in your non-SPA is include:

1. A reference to that same js file,
2. an element with the same id (#app) that Vue will use.

If you do this on each page of your application, the rest can be static HTML or whatever you need and Vue should run successfully on each page.

You do, however, need to perform the steps described in README.md (`npm install`, `npm run dev` etc.) whenever you develop to run webpack and all that. So if you previously just included Vue using a script tag, that's the part you're probably missing.

**Comment by chrisvfritz** [comment]
@brainyl You can see various examples integrating Vue into a backend application [here](https://github.com/chrisvfritz/rails-javascript-integrations). Those examples use 1.0 with Rails, but following the structure in those examples and also @mzgajner's advice, you should be set. 😃

**Comment by brainyl** [comment]
@mzgajner and @chrisvfritz, thank you for your response. I very much accustomed to the procedures and steps suggested. The sample main.js of this repo has the following content:
import Vue from 'vue'
import App from './App.vue'
new Vue({
  el: '#app',
  render: h => h(App)
})
And by doing this everything runs smoothly in Vue 2.0. However, previously in Vue 1.0 I could do something like: 
import Vue from 'vue'
new Vue({
  el: '#app'
})
Which now says "Failed to mount component: template or render function not defined. (found in root instance)". I already have so many components that uses code splitting and other features of webpack, which are bundled into one single JS file for my web app. I want to migrate them to Vue 2.0, what should I do?

**Comment by yyx990803** [comment]
@brainyl that was a bug in `vue-loader@9.2.1` which is now fixed in 9.2.2

**Comment by brainyl** [comment]
@yyx990803 thank you. Although, I tried 9.2.2 and it still throws that error.

**Comment by cnweibo** [comment]
@brainyl , you should use import Vue from 'vue/dist/vue' instead. That is a trick i just know, you have a try
